package formacion.mule.servicios;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import formacion.mule.on.ObjectFactory;
import formacion.mule.on.Pagina;
import formacion.mule.on.RespuestaPaises;

/**
 * This class was generated by Apache CXF 2.7.14
 * 2015-03-02T11:21:16.588+01:00
 * Generated source version: 2.7.14
 * 
 */
@WebService(targetNamespace = "urn:test-formacion:Direcciones", name = "DireccionesPort")
@XmlSeeAlso({ObjectFactory.class})
public interface Direcciones {

    @WebResult(name = "Respuesta", targetNamespace = "urn:test-formacion:Direcciones")
    @WebMethod(operationName = "PAISES", action = "PAISES")
    public RespuestaPaises paises(
        @WebParam(name = "Pagina", targetNamespace = "urn:test-formacion:Direcciones")
        Pagina pagina
    ) throws ServiceFault;
}
