package es.corpme.course.cxf2.contractfirst;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.0
 * 2015-05-19T13:45:25.644+02:00
 * Generated source version: 3.1.0
 * 
 */
@WebService(targetNamespace = "http://cxf.mulesoft.com/", name = "ServicePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface ServicePortType {

    @WebResult(name = "return", targetNamespace = "http://cxf.mulesoft.com/")
    @RequestWrapper(localName = "firstMethod", targetNamespace = "http://cxf.mulesoft.com/", className = "es.corpme.course.cxf2.contractfirst.FirstMethod")
    @WebMethod
    @ResponseWrapper(localName = "firstMethodResponse", targetNamespace = "http://cxf.mulesoft.com/", className = "es.corpme.course.cxf2.contractfirst.FirstMethodResponse")
    public es.corpme.course.cxf2.contractfirst.ReturnType firstMethod(
        @WebParam(name = "aNumber", targetNamespace = "http://cxf.mulesoft.com/")
        java.lang.Integer aNumber,
        @WebParam(name = "aString", targetNamespace = "http://cxf.mulesoft.com/")
        java.lang.String aString
    );
}
