package es.corpme.course.cxf2.contractfirst;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 3.1.0
 * 2015-05-19T13:45:25.764+02:00
 * Generated source version: 3.1.0
 * 
 */
@WebServiceClient(name = "Service", 
                  wsdlLocation = "classpath:contractfirst.wsdl",
                  targetNamespace = "http://cxf.mulesoft.com/") 
public class Service extends javax.xml.ws.Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://cxf.mulesoft.com/", "Service");
    public final static QName ServicePort = new QName("http://cxf.mulesoft.com/", "ServicePort");
    static {
        URL url = Service.class.getClassLoader().getResource("contractfirst.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "classpath:contractfirst.wsdl");
        }       
        WSDL_LOCATION = url;   
    }

    public Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    




    /**
     *
     * @return
     *     returns ServicePortType
     */
    @WebEndpoint(name = "ServicePort")
    public ServicePortType getServicePort() {
        return super.getPort(ServicePort, ServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServicePortType
     */
    @WebEndpoint(name = "ServicePort")
    public ServicePortType getServicePort(WebServiceFeature... features) {
        return super.getPort(ServicePort, ServicePortType.class, features);
    }

}
